pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -f ("/var/jenkins_home/workspace/Mvn_ex/simple-java-maven-app/pom.xml") -B -DskipTests clean package'
            }
        }

    }
}
